name: Action Test CI

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  test-ping-unstable:
    name: Test ping on Tailscale CLI Unstable
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use ephemeral authkey to join tailnet on unstable stream
        uses: ./
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY_AJHALILI2006 }}
          tags: "tag:gh-actions,tag:linux,tag:msft-azure,tag:ssh,tag:docker"
          version: "1.17.91"

      - name: Check for gildedguy.tailnet ad ping
        run: |
          tailscale status | grep -q gilded
          tailscale ping gildedguy || true